# Generated by Django 5.1.1 on 2024-09-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('attendee', 'attendee'), ('admin', 'admin'), ('superAdmin', 'superAdmin')], default='attendee', max_length=10),
        ),
    ]
